### ISSUE TITLE
The memory of the code

### ISSUE THREAD

**Issue by AiLearningCode** [DeLightCMU/CASD#5]
Hi,Nice work!

Thanks for releasing the code, I have a question about the GPU memory of this code. I ran the default parameter to train the network, like bs=1, net=vgg16. I have seen that the required GPU memory was 24G，When I  used four 1080ti to train the network,  I met the out of memory error, the memory of 1080ti is 11G. When are you going to release code of mutil gpu training ?

Thank you very much!

**Comment by Justinhzy** [comment]
Hi,
If you use 1080ti, please see here:https://github.com/vasgaowei/pytorch_MELM/issues/20. 
Based on other wsod repositories, it looks like 8 GPU training is much better than single GPU training. So I hope I can implement everything in MMdetection around Christmas.
