### ISSUE TITLE
About consistency loss

### ISSUE THREAD

**Issue by SongYii** [DeLightCMU/CASD#6]
Thank you for your outstanding work. 
During the training of the network, `self.ca_iw` is always False, I noticed that in  [network.py#L216](https://github.com/DeLightCMU/CASD/blob/d95a16ad1dc64fdbcd5333405b5825aaaaea156b/lib/nets/network.py#L216),  `self.ca_iw` is modified to False, but when `iteration> 45000`, ` self.ca_iw` also seems to be False. The result of my training is worse than the result in the paper. Is it because `ca_iw` has not been used? The return value [rampweight](https://github.com/DeLightCMU/CASD/blob/d95a16ad1dc64fdbcd5333405b5825aaaaea156b/lib/nets/network.py#L226) of the function that modifies `self.ca_iw` is also not used in the subsequent code, so I am not too clear about the logic of when to use `self.ca_iw`.

**Comment by Justinhzy** [comment]
Hi,
I recommend using CASD_IW after several epochs which is stable for different random seeds. Could you try to use self.ca_iw after iteration 45000 or later epoch?

**Comment by SongYii** [comment]
I used `self.ca_iw` in the later epoch, but the performance does not seem to change, probably 53~54. Looking forward to your complete version. Thank you.
