### ISSUE TITLE
Some issues about proposal files

### ISSUE THREAD

**Issue by longrongyang** [DeLightCMU/CASD#8]
Hello, your work is excellent! Proposal files provided by you contain four .pkl files. However, codes seemingly needs .mat file. Whether are proposal files incorrect? Thank you very much! And when I directly load .pkl file as proposals, there exits 'gt_classes', 'image_level_labels' and so on. However, I can not find these in your provided .pkl files. I do not know why. Can you provide the .mat file? Thank you very much!

**Comment by Justinhzy** [comment]
Hi,
you may find the mat file here(https://github.com/vasgaowei/pytorch_MELM).

**Comment by longrongyang** [comment]
OK, thank you very much!
